### ISSUE TITLE
Does not handle missing repository url.

### ISSUE THREAD

**Issue by remotezygote** [Leko/hothouse#103]
## Environment

- Version: `0.4.7`
- package manager: `yarn`
- directory structure: `yarn workspaces`

## Overview
When out-of-date packages are found, hothouse tries to get the repository url for each package, but some packages do not have a repository section at all (this is fairly common).

## Actual behavior
```sh
  hothouse:fetchReleases Try to fetch tag of wdio-mocha-framework@0.5.13 +0ms
  hothouse:fetchReleases Try to fetch tag of react-textarea-autosize@6.1.0 +0ms
  hothouse:fetchReleases Try to fetch tag of twitter-text@1.9.4 +0ms
TypeError: Cannot read property 'url' of undefined
    at Package.getRepositoryHttpsUrl (/Users/john/.config/yarn/global/node_modules/hothouse/dist/Package.js:54:58)
    at getUpdateDetail (/Users/john/.config/yarn/global/node_modules/hothouse/dist/tasks/fetchReleases.js:53:29)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Please report issue from here: https://github.com/Leko/hothouse/issues
TypeError: Cannot read property 'url' of undefined
    at Package.getRepositoryHttpsUrl (/Users/john/.config/yarn/global/node_modules/hothouse/dist/Package.js:54:58)
    at getUpdateDetail (/Users/john/.config/yarn/global/node_modules/hothouse/dist/tasks/fetchReleases.js:53:29)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Please report issue from here: https://github.com/Leko/hothouse/issues
```

## Expected behavior

No errors. Not sure what is after this since this is as far as I have gotten so far.

**Comment by remotezygote** [comment]
More info from `package.json`s:

`wdio-mocha-framework`:
```
  "repository": {
    "type": "git",
    "url": "git+https://github.com/webdriverio/wdio-mocha-framework.git"
  },
```

`react-textarea-autosize`:
`"repository": "andreypopp/react-textarea-autosize",`

`twitter-text `:
```
  "repository": {
    "type": "git",
    "url": "https://github.com/twitter/twitter-text-js.git"
  },
```

So not sure what is going on here...

**Comment by remotezygote** [comment]
Looks like possibly unreleased changes might fix this.

**Comment by remotezygote** [comment]
What is on master still does not work. I verified locally.

**Comment by Leko** [comment]
Thanks for reporting.

When repository.url is not present, hothouse should not try to fetch tag and releases.
I’ll fix this issue.

**Comment by Leko** [comment]
@remotezygote I'm sorry for late reply. I took a week off.

I fixed this issue by these commits.
https://github.com/Leko/hothouse/pull/107/commits/3e6fbe99e33ce7cf901bf036fd7ea99e4b64b9e9
https://github.com/Leko/hothouse/pull/107/commits/29d45473d0dcf8c7288339387106c76cb750f6b9
And I just released a new version of hothouse@0.4.8.

If you still have any problem, please re-open this issue.
Thanks.

**Comment by remotezygote** [comment]
No worries! Time off is important. Thanks a bunch! I'll try it now.

**Comment by remotezygote** [comment]
It works! Thanks so much!
